config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|es|fr/ do
    ['chichen', 'merida'].each do |hotel|
      ['galery', 'home', 'book', 'tours', 'directions', 'visit'].each do |nav|
        get("#{hotel}/#{nav}" => "hotels##{nav}")
      end
    end
    get 'hotels/main'
  end

  get '/:locale' => 'dashboard#index'

  root 'hotels#main'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

  	before_action :set_locale
 
  	def set_locale
		I18n.locale = params[:locale] || I18n.default_locale
 	end

 	def default_url_options(options = {})
	  	{ locale: I18n.locale }.merge options
	end

end

app/controllers/chichen_controller.rb
class ChichenController < ApplicationController
  def home
  end

  def galery
  end

  def book
  end

  def tours
  end

  def directions
  end

  def visit
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def main
  end

  def home
  end

  def galery
  end

  def book
  end

  def tours
  end

  def directions
  end

  def visit
  end
end

app/controllers/merida_controller.rb
class MeridaController < ApplicationController
  def home
  end

  def galery
  end

  def book
  end

  def tours
  end

  def directions
  end

  def visit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def is_active?(link_path)
		current_page?(link_path) ? "active" : ""
	end
end

app/helpers/chichen_helper.rb
module ChichenHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/merida_helper.rb
module MeridaHelper
end

app/views/chichen/book.html.erb
<h1>Chichen#book</h1>
<p>Find me in app/views/chichen/book.html.erb</p>

app/views/chichen/directions.html.erb
<h1>Chichen#directions</h1>
<p>Find me in app/views/chichen/directions.html.erb</p>

app/views/chichen/galery.html.erb
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1>Chichen Galery</h1>
    </div>
</div>
<!-- /.row -->

<hr>

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
</div>
<!-- /.row -->
<br>

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
</div>
<!-- /.row -->
<br>

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
</div>
<!-- /.row -->

<hr>

<!-- Pagination -->
<div class="row text-center">
    <div class="col-lg-12">
        <ul class="pagination">
            <li>
                <a href="#">&laquo;</a>
            </li>
            <li class="active">
                <a href="#">1</a>
            </li>
            <li>
                <a href="#">2</a>
            </li>
            <li>
                <a href="#">3</a>
            </li>
            <li>
                <a href="#">4</a>
            </li>
            <li>
                <a href="#">5</a>
            </li>
            <li>
                <a href="#">&raquo;</a>
            </li>
        </ul>
    </div>
</div>
<!-- /.row -->

app/views/chichen/home.html.erb
<h1>Chichen#home</h1>
<p>Find me in app/views/chichen/home.html.erb</p>

app/views/chichen/tours.html.erb
<h1>Chichen#tours</h1>
<p>Find me in app/views/chichen/tours.html.erb</p>

app/views/chichen/visit.html.erb
<h1>Chichen#visit</h1>
<p>Find me in app/views/chichen/visit.html.erb</p>

app/views/hotels/book.html.erb
<h1>Merida#book</h1>
<p>Find me in app/views/merida/book.html.erb</p>

app/views/hotels/directions.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body">
				<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3725.6503472443587!2d-89.62053064816286!3d20.966552240288845!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x33efa7127b976f2f!2sHotel+Dolores+Alba!5e0!3m2!1sen!2smx!4v1424916296035" width="525" height="300" frameborder="0" style="border:0"></iframe>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body">
				<h4><%= t :merida_by_plane_or_bus %></h4>
				<p><%= t :merida_by_plane_or_bus_text %></p>
				<h4><%= t :merida_from_the_airport %></h4>
				<p><%= t :merida_from_the_airport_text %></p>
				<h4><%= t :merida_contact %></h4>
				<p></p>
				<p><a href="#"><%= t :merida_get_printable_map %></a>
			</div>
		</div>
	</div>
</div>
		

app/views/hotels/galery.html.erb
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1>Merida Galery</h1>
    </div>
</div>
<!-- /.row -->

<hr>

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
</div>
<!-- /.row -->
<br>

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
</div>
<!-- /.row -->
<br>

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
</div>
<!-- /.row -->

<hr>

<!-- Pagination -->
<div class="row text-center">
    <div class="col-lg-12">
        <ul class="pagination">
            <li>
                <a href="#">&laquo;</a>
            </li>
            <li class="active">
                <a href="#">1</a>
            </li>
            <li>
                <a href="#">2</a>
            </li>
            <li>
                <a href="#">3</a>
            </li>
            <li>
                <a href="#">4</a>
            </li>
            <li>
                <a href="#">5</a>
            </li>
            <li>
                <a href="#">&raquo;</a>
            </li>
        </ul>
    </div>
</div>
<!-- /.row -->

app/views/hotels/home.html.erb
<h1>Merida#home</h1>
<p>Find me in app/views/merida/home.html.erb</p>

app/views/hotels/main.html.erb
<div class="container text-center">
	<button type="button" class="btn btn-default"><%= link_to "Merida", merida_home_path %></button>
 	<button type="button" class="btn btn-default"><%= link_to "Chichen", chichen_home_path %></button>
</div>

app/views/hotels/tours.html.erb
<h1>Merida#tours</h1>
<p>Find me in app/views/merida/tours.html.erb</p>

app/views/hotels/visit.html.erb
<h1>Merida#visit</h1>
<p>Find me in app/views/merida/visit.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoralbaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style><%= yield :stylesheets %></style>

  <!--Script de Font Arnold Boed -->
  <script type="text/javascript" src="http://fast.fonts.net/jsapi/27fed573-bdec-4d31-9c36-33a6f97a706d.js"></script>
</head>
<body>
	
	<%= content_for?(:content) ? yield(:content) : yield %>
	
</body>
</html>

app/views/layouts/chichen.html.erb
<% content_for :stylesheets do %>
  	<!-- TODO special stylesheets -->
<% end %>

<% content_for :content do %>
<!-- NAVIGATION -->
	<nav class="navbar navbar-default">
	  <div class="container container-fluid">
	    <!-- Dolores Alba Logo -->
		    <div class="navbar-header">
		      	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
		      	<a class="navbar-brand" id="doralba-logo" href="<%= hotels_main_path %>">Dolores Alba</a>
		    </div>

		    <!-- Menus -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		    	<!-- Menus a la izquierda -->
	      		<ul class="nav navbar-nav">
			        <li class="<%= is_active?(chichen_home_path) %>"><%= link_to t("Chichen"), chichen_home_path %></li>
			        <li class="<%= is_active?(chichen_galery_path) %>"><%= link_to t(:Gallery), chichen_galery_path %></li>
			        <li class="<%= is_active?(chichen_visit_path) %>"><%= link_to t(:Visit), chichen_visit_path %></li>
			        <li class="<%= is_active?(chichen_tours_path) %>"><%= link_to t(:Tours), chichen_tours_path %></li>
			        <li class="<%= is_active?(chichen_directions_path) %>"><%= link_to t(:Directions), chichen_directions_path %></li>
			        <li class="<%= is_active?(chichen_book_path) %>"><%= link_to t(:Book), chichen_book_path %></li>
	      		</ul>
	      		<!-- Menus a la derecha -->
	      		<ul class="nav navbar-nav navbar-right">
	        		<li class="dropdown">
	          			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Language <span class="caret"></span></a>
			          	<ul class="dropdown-menu" role="menu">
				          	<li><%= link_to "English", params.merge({:locale => 'en'}) %></li>
				            <li><%= link_to "Español", params.merge({:locale => 'es'}) %></li>
				            <li><%= link_to "Français", params.merge({:locale => 'fr'}) %></li>
			          	</ul>
	        		</li>
		        	<li class="dropdown">
		          		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Hotel <span class="caret"></span></a>
		          		<ul class="dropdown-menu" role="menu">
				          	<li><%= link_to "Merida", merida_home_path %></li>
				            <li><%= link_to "Chichen", chichen_home_path %></li>
		          		</ul>
	        		</li>
	      		</ul>
	    	</div>
	  	</div>
	</nav>

	<div class="container">
  		<%= content_for?(:chichen_content) ? yield(:chichen_content) : yield %>
  	</div>
  	<footer>
		<div class="row text-center">
            <div class="col-lg-12">
                <p>Copyright &copy; Dolores Alba 2015</p>
            </div>
        </div>
	</footer>

<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/merida.html.erb
<% content_for :stylesheets do %>
  	<!-- TODO special stylesheets -->
<% end %>

<% content_for :content do %>
<!-- NAVIGATION -->
	<nav class="navbar navbar-default">
	  <div class="container container-fluid">
	    <!-- Dolores Alba Logo -->
		    <div class="navbar-header">
		      	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
		      	<a class="navbar-brand" id="doralba-logo" href="<%= hotels_main_path %>">Dolores Alba</a>
		    </div>

		    <!-- Menus -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		    	<!-- Menus a la izquierda -->
	      		<ul class="nav navbar-nav">
			        <li class="<%= is_active?(merida_home_path) %>"><%= link_to "Merida", merida_home_path %></li>
			        <li class="<%= is_active?(merida_galery_path) %>"><%= link_to t(:gallery), merida_galery_path %></li>
			        <li class="<%= is_active?(merida_visit_path) %>"><%= link_to t(:visit), merida_visit_path %></li>
			        <li class="<%= is_active?(merida_tours_path) %>"><%= link_to t(:tours), merida_tours_path %></li>
			        <li class="<%= is_active?(merida_directions_path) %>"><%= link_to t(:directions), merida_directions_path %></li>
			        <li class="<%= is_active?(merida_book_path) %>"><%= link_to t(:book), merida_book_path %></li>
	      		</ul>
	      		<!-- Menus a la derecha -->
	      		<ul class="nav navbar-nav navbar-right">
	        		<li class="dropdown">
	          			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Language <span class="caret"></span></a>
			          	<ul class="dropdown-menu" role="menu">
				          	<li><%= link_to "English", params.merge({:locale => 'en'}) %></li>
				            <li><%= link_to "Español", params.merge({:locale => 'es'}) %></li>
				            <li><%= link_to "Français", params.merge({:locale => 'fr'}) %></li>
			          	</ul>
	        		</li>
		        	<li class="dropdown">
		          		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Hotel <span class="caret"></span></a>
		          		<ul class="dropdown-menu" role="menu">
				          	<li><%= link_to "Merida", merida_home_path %></li>
				            <li><%= link_to "Chichen", chichen_home_path %></li>
		          		</ul>
	        		</li>
	      		</ul>
	    	</div>
	  	</div>
	</nav>

	<div class="container">
  		<%= content_for?(:merida_content) ? yield(:merida_content) : yield %>
  	</div>
  	<footer>
		<div class="row text-center">
            <div class="col-lg-12">
                <p>Copyright &copy; Dolores Alba 2015</p>
            </div>
        </div>
	</footer>

<% end %>

<%= render template: "layouts/application" %>

app/views/merida/book.html.erb
<h1>Merida#book</h1>
<p>Find me in app/views/merida/book.html.erb</p>

app/views/merida/directions.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body">
				<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3725.6503472443587!2d-89.62053064816286!3d20.966552240288845!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x33efa7127b976f2f!2sHotel+Dolores+Alba!5e0!3m2!1sen!2smx!4v1424916296035" width="525" height="300" frameborder="0" style="border:0"></iframe>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body">
				<h4><%= t :merida_by_plane_or_bus %></h4>
				<p><%= t :merida_by_plane_or_bus_text %></p>
				<h4><%= t :merida_from_the_airport %></h4>
				<p><%= t :merida_from_the_airport_text %></p>
				<h4><%= t :merida_contact %></h4>
				<p></p>
				<p><a href="#"><%= t :merida_get_printable_map %></a>
			</div>
		</div>
	</div>
</div>
		

app/views/merida/galery.html.erb
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1>Merida Galery</h1>
    </div>
</div>
<!-- /.row -->

<hr>

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
</div>
<!-- /.row -->
<br>

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
</div>
<!-- /.row -->
<br>

<!-- Projects Row -->
<div class="row">
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
    <div class="col-md-3 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="http://placehold.it/750x450" alt="">
        </a>
    </div>
</div>
<!-- /.row -->

<hr>

<!-- Pagination -->
<div class="row text-center">
    <div class="col-lg-12">
        <ul class="pagination">
            <li>
                <a href="#">&laquo;</a>
            </li>
            <li class="active">
                <a href="#">1</a>
            </li>
            <li>
                <a href="#">2</a>
            </li>
            <li>
                <a href="#">3</a>
            </li>
            <li>
                <a href="#">4</a>
            </li>
            <li>
                <a href="#">5</a>
            </li>
            <li>
                <a href="#">&raquo;</a>
            </li>
        </ul>
    </div>
</div>
<!-- /.row -->

app/views/merida/home.html.erb
<h1>Merida#home</h1>
<p>Find me in app/views/merida/home.html.erb</p>

app/views/merida/tours.html.erb
<h1>Merida#tours</h1>
<p>Find me in app/views/merida/tours.html.erb</p>

app/views/merida/visit.html.erb
<h1>Merida#visit</h1>
<p>Find me in app/views/merida/visit.html.erb</p>